DROP TRIGGER IF EXISTS contact_links_updated_at ON contact_links;
DROP TRIGGER IF EXISTS profile_updated_at ON profile;
DROP TRIGGER IF EXISTS blog_posts_slug_lock ON blog_posts;
DROP TRIGGER IF EXISTS blog_posts_updated_at ON blog_posts;
DROP TRIGGER IF EXISTS projects_slug_lock ON projects;
DROP TRIGGER IF EXISTS projects_updated_at ON projects;
DROP TRIGGER IF EXISTS project_links_updated_at ON project_links;
DROP TRIGGER IF EXISTS taxonomy_terms_updated_at ON taxonomy_terms;
DROP TRIGGER IF EXISTS media_assets_updated_at ON media_assets;
DROP TRIGGER IF EXISTS users_updated_at ON users;
DROP FUNCTION IF EXISTS lock_published_slug();
DROP FUNCTION IF EXISTS set_updated_at();
DROP TABLE IF EXISTS slug_redirects;
DROP TABLE IF EXISTS contact_links;
DROP TABLE IF EXISTS profile;
DROP TABLE IF EXISTS project_links;
DROP TABLE IF EXISTS post_categories;
DROP TABLE IF EXISTS post_tags;
DROP TABLE IF EXISTS project_categories;
DROP TABLE IF EXISTS project_tags;
DROP TABLE IF EXISTS blog_posts;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS taxonomy_terms;
DROP TABLE IF EXISTS media_assets;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS redirect_content_type;
DROP TYPE IF EXISTS taxonomy_kind;
DROP TYPE IF EXISTS contact_link_kind;
DROP TYPE IF EXISTS project_link_kind;
DROP TYPE IF EXISTS project_availability;
DROP TYPE IF EXISTS project_stage;
DROP TYPE IF EXISTS content_status;
DROP TYPE IF EXISTS user_status;
DROP TYPE IF EXISTS user_role;
